version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    networks:
      - my_network

  confluence:
    image: atlassian/confluence-server
    environment:
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/mydatabase
      - ATL_JDBC_USER=myuser
      - ATL_JDBC_PASSWORD=mypassword
    ports:
      - "8090:8090"
    networks:
      - my_network
    depends_on:
      - postgres
